#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef UYALIBEAUTYSDK_SWIFT_H
#define UYALIBEAUTYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UyaliBeautySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreVideo;
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UyaliBeautySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 美妆：腮红类型。
/// Makeup: blush type.
typedef SWIFT_ENUM(NSInteger, MakeupBlushType, open) {
/// 无。
/// None.
  MakeupBlushTypeBlush_none = 0,
/// 无辜：奶杏色。
/// Innocent: milky apricot.
  MakeupBlushTypeBlush_wugu_naixingse = 1,
/// 无辜：奶橘色。
/// Innocent: milky orange.
  MakeupBlushTypeBlush_wugu_naijuse = 2,
/// 无辜：蜜桃橘。
/// Innocent: peach orange.
  MakeupBlushTypeBlush_wugu_mitaoju = 3,
/// 无辜：烟熏玫瑰。
/// Innocent: smoky rose.
  MakeupBlushTypeBlush_wugu_yanxunmeigui = 4,
/// 无辜：牛奶草莓。
/// Innocent: milk strawberry.
  MakeupBlushTypeBlush_wugu_niunaicaomei = 5,
/// 茶艺：奶杏色。
/// Chayi: milky apricot.
  MakeupBlushTypeBlush_chayi_naixingse = 6,
/// 茶艺：奶橘色。
/// Chayi: milky orange.
  MakeupBlushTypeBlush_chayi_naijuse = 7,
/// 茶艺：蜜桃橘。
/// Chayi: peach orange.
  MakeupBlushTypeBlush_chayi_mitaoju = 8,
/// 茶艺：烟熏玫瑰。
/// Chayi: smoky rose.
  MakeupBlushTypeBlush_chayi_yanxunmeigui = 9,
/// 茶艺：牛奶草莓。
/// Chayi: milk strawberry.
  MakeupBlushTypeBlush_chayi_niunaicaomei = 10,
/// 初恋：奶杏色。
/// First love: milky apricot.
  MakeupBlushTypeBlush_chulian_naixingse = 11,
/// 初恋：奶橘色。
/// First love: milky orange.
  MakeupBlushTypeBlush_chulian_naijuse = 12,
/// 初恋：蜜桃橘。
/// First love: peach orange.
  MakeupBlushTypeBlush_chulian_mitaoju = 13,
/// 初恋：烟熏玫瑰。
/// First love: smoky rose.
  MakeupBlushTypeBlush_chulian_yanxunmeigui = 14,
/// 初恋：牛奶草莓。
/// First love: milk strawberry.
  MakeupBlushTypeBlush_chulian_niunaicaomei = 15,
/// 纯情：奶杏色。
/// Pure: milky apricot.
  MakeupBlushTypeBlush_chunqing_naixingse = 16,
/// 纯情：奶橘色。
/// Pure: milky orange.
  MakeupBlushTypeBlush_chunqing_naijuse = 17,
/// 纯情：蜜桃橘。
/// Pure: peach orange.
  MakeupBlushTypeBlush_chunqing_mitaoju = 18,
/// 纯情：烟熏玫瑰。
/// Pure: smoky rose.
  MakeupBlushTypeBlush_chunqing_yanxunmeigui = 19,
/// 纯情：牛奶草莓。
/// Pure: milk strawberry.
  MakeupBlushTypeBlush_chunqing_niunaicaomei = 20,
/// 奇迹：奶杏色。
/// Miracle: milky apricot.
  MakeupBlushTypeBlush_qiji_naixingse = 21,
/// 奇迹：奶橘色。
/// Miracle: milky orange.
  MakeupBlushTypeBlush_qiji_naijuse = 22,
/// 奇迹：蜜桃橘。
/// Miracle: peach orange.
  MakeupBlushTypeBlush_qiji_mitaoju = 23,
/// 奇迹：烟熏玫瑰。
/// Miracle: smoky rose.
  MakeupBlushTypeBlush_qiji_yanxunmeigui = 24,
/// 奇迹：牛奶草莓。
/// Miracle: milk strawberry.
  MakeupBlushTypeBlush_qiji_niunaicaomei = 25,
/// 少女：奶杏色。
/// Girlish: milky apricot.
  MakeupBlushTypeBlush_shaonv_naixingse = 26,
/// 少女：奶橘色。
/// Girlish: milky orange.
  MakeupBlushTypeBlush_shaonv_naijuse = 27,
/// 少女：蜜桃橘。
/// Girlish: peach orange.
  MakeupBlushTypeBlush_shaonv_mitaoju = 28,
/// 少女：烟熏玫瑰。
/// Girlish: smoky rose.
  MakeupBlushTypeBlush_shaonv_yanxunmeigui = 29,
/// 少女：牛奶草莓。
/// Girlish: milk strawberry.
  MakeupBlushTypeBlush_shaonv_niunaicaomei = 30,
/// 无辜：马卡龙粉。
/// Innocent: macaron pink.
  MakeupBlushTypeBlush_wugu_makalongfen = 31,
/// 茶艺：马卡龙粉。
/// Chayi: macaron pink.
  MakeupBlushTypeBlush_chayi_makalongfen = 32,
/// 初恋：马卡龙粉。
/// First love: macaron pink.
  MakeupBlushTypeBlush_chulian_makalongfen = 33,
/// 纯情：马卡龙粉。
/// Pure: macaron pink.
  MakeupBlushTypeBlush_chunqing_makalongfen = 34,
/// 奇迹：马卡龙粉。
/// Miracle: macaron pink.
  MakeupBlushTypeBlush_qiji_makalongfen = 35,
/// 少女：马卡龙粉。
/// Girlish: macaron pink.
  MakeupBlushTypeBlush_shaonv_makalongfen = 36,
};

/// 美妆：眉毛类型。
/// Makeup: eyebrow type.
typedef SWIFT_ENUM(NSInteger, MakeupEyebrowType, open) {
/// 无。
/// None.
  MakeupEyebrowTypeEyebrow_none = 0,
/// 标准眉。
/// Standard brow.
  MakeupEyebrowTypeEyebrow_biaozhun = 1,
/// 蹙颦眉。
/// Cupin brow.
  MakeupEyebrowTypeEyebrow_cupin = 2,
/// 罥烟眉。
/// Juanyan brow.
  MakeupEyebrowTypeEyebrow_juanyan = 3,
/// 流星眉。
/// Liuxing brow.
  MakeupEyebrowTypeEyebrow_liuxing = 4,
/// 柳叶眉。
/// Willow-leaf brow.
  MakeupEyebrowTypeEyebrow_liuye = 5,
/// 秋波眉。
/// Qiubo brow.
  MakeupEyebrowTypeEyebrow_qiubo = 6,
/// 弯月眉。
/// Crescent brow.
  MakeupEyebrowTypeEyebrow_wanyue = 7,
/// 新月眉。
/// New-moon brow.
  MakeupEyebrowTypeEyebrow_xinyue = 8,
/// 野生眉。
/// Natural brow.
  MakeupEyebrowTypeEyebrow_yesheng = 9,
/// 远山眉。
/// Yuanshan brow.
  MakeupEyebrowTypeEyebrow_yuanshan = 10,
};

/// 美妆：眼妆类型。
/// Makeup: eyeshadow type.
typedef SWIFT_ENUM(NSInteger, MakeupEyeshadowType, open) {
/// 无。
/// None.
  MakeupEyeshadowTypeEyeshadow_none = 0,
/// 大地色。
/// Earth tone.
  MakeupEyeshadowTypeEyeshadow_dadise = 1,
/// 复古色。
/// Vintage tone.
  MakeupEyeshadowTypeEyeshadow_fuguse = 2,
/// 方糖粉。
/// Sugar-cube pink.
  MakeupEyeshadowTypeEyeshadow_fangtangfen = 3,
/// 活力橘。
/// Vivid orange.
  MakeupEyeshadowTypeEyeshadow_huoliju = 4,
/// 金棕色。
/// Golden brown.
  MakeupEyeshadowTypeEyeshadow_jinzongse = 5,
/// 朋克棕。
/// Punk brown.
  MakeupEyeshadowTypeEyeshadow_pengkezong = 6,
/// 甜橙色。
/// Sweet orange.
  MakeupEyeshadowTypeEyeshadow_tianchengse = 7,
/// 星光粉。
/// Starlight pink.
  MakeupEyeshadowTypeEyeshadow_xingguangfen = 8,
/// 烟粉色。
/// Smoky pink.
  MakeupEyeshadowTypeEyeshadow_yanfense = 9,
/// 野蔷薇色。
/// Wild rose.
  MakeupEyeshadowTypeEyeshadow_yeqiangweise = 10,
/// 元气橙。
/// Fresh orange.
  MakeupEyeshadowTypeEyeshadow_yuanqicheng = 11,
};

/// 美妆：美瞳类型。
/// Makeup: colored contact lens type.
typedef SWIFT_ENUM(NSInteger, MakeupPupilType, open) {
/// 无。
/// None.
  MakeupPupilTypePupil_none = 0,
/// 胶片棕。
/// Film brown.
  MakeupPupilTypePupil_jiaopianzong = 1,
/// 蜜糖棕。
/// Honey brown.
  MakeupPupilTypePupil_mitangzong = 2,
/// 星夜蓝。
/// Starry blue.
  MakeupPupilTypePupil_xingyelan = 3,
/// 极昼黑。
/// Polar-day black.
  MakeupPupilTypePupil_jizhouhei = 4,
/// 忽扰灰。
/// Wurao gray.
  MakeupPupilTypePupil_wuraohui = 5,
/// 春日粉。
/// Spring pink.
  MakeupPupilTypePupil_chunrifen = 6,
/// 甜茶绿。
/// Sweet tea green.
  MakeupPupilTypePupil_tianchalv = 7,
/// 四叶草绿。
/// Clover green.
  MakeupPupilTypePupil_siyecaolv = 8,
/// 旷野蓝。
/// Field blue.
  MakeupPupilTypePupil_kuangyelan = 9,
/// 蔷薇粉灰。
/// Rose pink-gray.
  MakeupPupilTypePupil_qiangweifenhui = 10,
/// 海风蓝。
/// Sea-breeze blue.
  MakeupPupilTypePupil_haifenglan = 11,
/// 月球棕。
/// Moon brown.
  MakeupPupilTypePupil_yueqiuzong = 12,
};

/// 美妆：口红类型。
/// Makeup: lipstick type.
typedef SWIFT_ENUM(NSInteger, MakeupRougeType, open) {
/// 无。
/// None.
  MakeupRougeTypeRouge_none = 0,
/// 梅子色。
/// Plum.
  MakeupRougeTypeRouge_meizise = 1,
/// 豆沙粉。
/// Bean-paste pink.
  MakeupRougeTypeRouge_doushafen = 2,
/// 复古色。
/// Vintage tone.
  MakeupRougeTypeRouge_fuguse = 3,
/// 鬼魅红。
/// Phantom red.
  MakeupRougeTypeRouge_guimeihong = 4,
/// 浆果色。
/// Berry.
  MakeupRougeTypeRouge_jiangguose = 5,
/// 南瓜色。
/// Pumpkin.
  MakeupRougeTypeRouge_nanguase = 6,
/// 石榴红。
/// Pomegranate red.
  MakeupRougeTypeRouge_shiliuhong = 7,
/// 蜜桃色。
/// Peach.
  MakeupRougeTypeRouge_mitaose = 8,
/// 珊瑚色。
/// Coral.
  MakeupRougeTypeRouge_shanhuse = 9,
/// 星光红。
/// Starlight red.
  MakeupRougeTypeRouge_xingguanghong = 10,
/// 暗夜紫。
/// Midnight purple.
  MakeupRougeTypeRouge_anyezi = 11,
/// 少女粉。
/// Girlish pink.
  MakeupRougeTypeRouge_shaonvfen = 12,
};

SWIFT_ENUM_FWD_DECL(NSInteger, UyaliBeautyLicenseStatus)
@class NSString;
@class UyaliBeautyLicenseResult;
@class NSURL;
SWIFT_ENUM_FWD_DECL(NSInteger, UyaliBeautyFeature)
@class NSValue;
@class NSNumber;
/// UyaliBeauty SDK 主入口。
/// Main entry point of the UyaliBeauty SDK.
SWIFT_CLASS("_TtC14UyaliBeautySDK17UyaliBeautyEngine")
@interface UyaliBeautyEngine : NSObject
/// 当前 License 状态。
/// Current license status.
@property (nonatomic, readonly) enum UyaliBeautyLicenseStatus licenseStatus;
/// 当前 License 状态说明。
/// Human-readable message for the current license status.
@property (nonatomic, readonly, copy) NSString * _Nonnull licenseMessage;
/// 本次会话剩余试用秒数。
/// Remaining trial seconds for the current session.
@property (nonatomic, readonly) NSTimeInterval licenseTrialSecondsRemaining;
/// 当前渲染是否需要显示试用水印。
/// Whether the current rendering should display a trial watermark.
@property (nonatomic, readonly) BOOL licenseRequiresWatermark;
/// 使用 License 字符串激活 SDK。
/// Activates the SDK with a license string.
- (UyaliBeautyLicenseResult * _Nonnull)activateLicense:(NSString * _Nonnull)licenseString SWIFT_WARN_UNUSED_RESULT;
/// 从本地文件加载并激活 License。
/// Loads and activates a license from a local file.
- (UyaliBeautyLicenseResult * _Nonnull)loadLicenseAt:(NSURL * _Nonnull)fileURL SWIFT_WARN_UNUSED_RESULT;
/// 查询当前 License 是否允许使用指定功能。
/// Returns whether the current license allows the specified feature.
- (BOOL)canUseFeature:(enum UyaliBeautyFeature)feature SWIFT_WARN_UNUSED_RESULT;
/// 是否启用人体轮廓调试输出。
/// Enables body contour debug output.
@property (nonatomic) BOOL bodyContourDebugEnabled;
/// 静态图片处理时是否复用上一帧人体姿态结果。
/// Reuses the previous body pose result when processing static images.
@property (nonatomic) BOOL staticImageBodyPoseReuseEnabled;
/// 是否启用人脸轮廓调试输出。
/// Enables face contour debug output.
@property (nonatomic) BOOL faceContourDebugEnabled;
/// 最近一次检测到的人脸轮廓点。
/// Face contour points from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSValue *> * _Nonnull latestFaceContourPoints;
/// 最近一次检测到的人脸关键点。
/// Face landmark points from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSValue *> * _Nonnull latestFaceLandmarkPoints;
/// 最近一次检测到的人脸关键点标签。
/// Face landmark labels from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull latestFaceLandmarkLabels;
/// 最近一次检测到的人脸轮廓标签。
/// Face contour labels from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull latestFaceContourLabels;
/// 最近一次人脸轮廓调试信息。
/// Face contour debug information from the latest detection.
@property (nonatomic, readonly, copy) NSString * _Nonnull latestFaceContourDebugInfo;
/// 最近一次检测到的人体轮廓点。
/// Body contour points from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSValue *> * _Nonnull latestBodyContourPoints;
/// 最近一次检测到的人体分部轮廓点。
/// Body-part contour points from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSValue *> * _Nonnull latestBodyPartContourPoints;
/// 最近一次检测到的人体分部轮廓标签。
/// Body-part contour labels from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull latestBodyPartContourLabels;
/// 最近一次检测到的人体关键点。
/// Body landmark points from the latest detection.
@property (nonatomic, readonly, copy) NSArray<NSValue *> * _Nonnull latestBodyLandmarkPoints;
/// 最近一次人体轮廓调试信息。
/// Body contour debug information from the latest detection.
@property (nonatomic, readonly, copy) NSString * _Nonnull latestBodyContourDebugInfo;
/// 小头，参数范围：0.0 - 100.0。
/// Head reduction amount. Range: 0.0 - 100.0.
@property (nonatomic) float headReduce_delta;
/// 瘦脸，参数范围：0.0 - 100.0。
/// Face slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float faceThin_delta;
/// 窄脸，参数范围：0.0 - 100.0。
/// Face narrowing amount. Range: 0.0 - 100.0.
@property (nonatomic) float faceNarrow_delta;
/// V脸，参数范围：0.0 - 100.0。
/// V-line face amount. Range: 0.0 - 100.0.
@property (nonatomic) float faceV_delta;
/// 小脸，参数范围：0.0 - 100.0。
/// Small face amount. Range: 0.0 - 100.0.
@property (nonatomic) float faceSmall_delta;
/// 下巴，参数范围：-50.0 - 50.0。
/// Chin adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float chin_delta;
/// 额头，参数范围：-50.0 - 50.0。
/// Forehead adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float forehead_delta;
/// 颧骨，参数范围：-50.0 - 50.0。
/// Cheekbone adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float cheekbone_delta;
/// 大眼，参数范围：0.0 - 100.0。
/// Eye enlargement amount. Range: 0.0 - 100.0.
@property (nonatomic) float eyeBig_delta;
/// 眼距，参数范围：-50.0 - 50.0。
/// Eye distance adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float eyeDistance_delta;
/// 内眼角，参数范围：0.0 - 100.0。
/// Inner eye-corner adjustment amount. Range: 0.0 - 100.0.
@property (nonatomic) float eyeCorner_delta;
/// 眼睑下至，参数范围：0.0 - 100.0。
/// Lower eyelid adjustment amount. Range: 0.0 - 100.0.
@property (nonatomic) float eyelidDown_delta;
/// 瘦鼻，参数范围：0.0 - 100.0。
/// Nose slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float noseThin_delta;
/// 鼻翼，参数范围：0.0 - 100.0。
/// Nose wing adjustment amount. Range: 0.0 - 100.0.
@property (nonatomic) float noseWing_delta;
/// 长鼻，参数范围：-50.0 - 50.0。
/// Nose length adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float noseLong_delta;
/// 山根，参数范围：0.0 - 100.0。
/// Nose bridge/root adjustment amount. Range: 0.0 - 100.0.
@property (nonatomic) float noseRoot_delta;
/// 眉间距，参数范围：-50.0 - 50.0。
/// Eyebrow distance adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float eyebrowDistance_delta;
/// 眉粗细，参数范围：-50.0 - 50.0。
/// Eyebrow thickness adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float eyebrowThin_delta;
/// 嘴型，参数范围：-50.0 - 50.0。
/// Mouth shape adjustment amount. Range: -50.0 - 50.0.
@property (nonatomic) float mouth_delta;
/// 瘦身，参数范围：0.0 - 100.0。
/// Body slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float bodySlim_delta;
/// 瘦腰，参数范围：0.0 - 100.0。
/// Waist slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float waistSlim_delta;
/// 瘦腿，参数范围：0.0 - 100.0。
/// Leg slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float legSlim_delta;
/// 窄肩，参数范围：0.0 - 100.0。
/// Shoulder narrowing amount. Range: 0.0 - 100.0.
@property (nonatomic) float shoulderNarrow_delta;
/// 瘦手臂，参数范围：0.0 - 100.0。
/// Arm slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float armSlim_delta;
/// 小腿修饰，参数范围：0.0 - 100.0。
/// Calf refinement amount. Range: 0.0 - 100.0.
@property (nonatomic) float calfSlim_delta;
/// 收腹，参数范围：0.0 - 100.0。
/// Abdomen slimming amount. Range: 0.0 - 100.0.
@property (nonatomic) float abdomenSlim_delta;
/// 长腿，参数范围：0.0 - 100.0。
/// Leg lengthening amount. Range: 0.0 - 100.0.
@property (nonatomic) float legLong_delta;
/// 增高，参数范围：0.0 - 100.0。
/// Height enhancement amount. Range: 0.0 - 100.0.
@property (nonatomic) float bodyHeight_delta;
/// 腿型矫正，参数范围：0.0 - 100.0。
/// Leg shape correction amount. Range: 0.0 - 100.0.
@property (nonatomic) float legShape_delta;
/// 天鹅颈，参数范围：0.0 - 100.0。
/// Neck lengthening amount. Range: 0.0 - 100.0.
@property (nonatomic) float neckLength_delta;
/// 直角肩，参数范围：0.0 - 100.0。
/// Shoulder shaping amount. Range: 0.0 - 100.0.
@property (nonatomic) float shoulderShape_delta;
/// 美白，参数范围：0.0 - 100.0。
/// Skin whitening amount. Range: 0.0 - 100.0.
@property (nonatomic) float white_delta;
/// 磨皮，参数范围：0.0 - 100.0。
/// Skin smoothing amount. Range: 0.0 - 100.0.
@property (nonatomic) float skin_delta;
/// 亮眼，参数范围：0.0 - 100.0。
/// Eye brightening amount. Range: 0.0 - 100.0.
@property (nonatomic) float eyeBright_delta;
/// 白牙，参数范围：0.0 - 100.0。
/// Teeth whitening amount. Range: 0.0 - 100.0.
@property (nonatomic) float teethBright_delta;
/// 去黑眼圈，参数范围：0.0 - 100.0。
/// Dark-circle reduction amount. Range: 0.0 - 100.0.
@property (nonatomic) float darkCircle_delta;
/// 法令纹功能已移除，保留参数仅用于兼容旧调用。
/// Nasolabial fold removal has been removed; this parameter is kept only for backward compatibility.
@property (nonatomic) float nasolabialFold_delta;
/// 眉毛强度，参数范围：0.0 - 100.0。
/// Eyebrow makeup intensity. Range: 0.0 - 100.0.
@property (nonatomic) float makeup_eyebrow_delta;
/// 眉毛类型。
/// Eyebrow makeup type.
@property (nonatomic) enum MakeupEyebrowType makeup_eyebrow_type;
/// 眼妆强度，参数范围：0.0 - 100.0。
/// Eyeshadow makeup intensity. Range: 0.0 - 100.0.
@property (nonatomic) float makeup_eyeshadow_delta;
/// 眼妆类型。
/// Eyeshadow makeup type.
@property (nonatomic) enum MakeupEyeshadowType makeup_eyeshadow_type;
/// 美瞳强度，参数范围：0.0 - 100.0。
/// Colored contact lens intensity. Range: 0.0 - 100.0.
@property (nonatomic) float makeup_pupil_delta;
/// 美瞳类型。
/// Colored contact lens type.
@property (nonatomic) enum MakeupPupilType makeup_pupil_type;
/// 腮红强度，参数范围：0.0 - 100.0。
/// Blush makeup intensity. Range: 0.0 - 100.0.
@property (nonatomic) float makeup_blush_delta;
/// 腮红类型。
/// Blush makeup type.
@property (nonatomic) enum MakeupBlushType makeup_blush_type;
/// 口红强度，参数范围：0.0 - 100.0。
/// Lipstick makeup intensity. Range: 0.0 - 100.0.
@property (nonatomic) float makeup_rouge_delta;
/// 口红类型。
/// Lipstick makeup type.
@property (nonatomic) enum MakeupRougeType makeup_rouge_type;
/// 创建 UyaliBeauty 引擎实例。
/// Creates a UyaliBeauty engine instance.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 直接在传入的 CVPixelBuffer 上处理图像，当前仅支持 RGBA 格式。
/// Processes the input CVPixelBuffer in place. Currently supports RGBA format only.
- (void)processWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer;
/// 处理传入的 CVPixelBuffer 并返回输出图像。
/// Processes the input CVPixelBuffer and returns the output pixel buffer.
- (CVPixelBufferRef _Nonnull)processWithOutputWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer SWIFT_WARN_UNUSED_RESULT;
/// 重置所有滤镜参数。
/// Resets all filter parameters.
- (void)resetAllFilters;
@end

/// 可被 License 控制的 SDK 功能。
/// SDK features controlled by the license.
typedef SWIFT_ENUM_NAMED(NSInteger, UyaliBeautyFeature, "UyaliBeautyFeature", open) {
/// 美白。
/// Skin whitening.
  UyaliBeautyFeatureWhiten = 0,
/// 磨皮。
/// Skin smoothing.
  UyaliBeautyFeatureSmooth = 1,
/// 进阶美颜能力，例如亮眼、白牙、去黑眼圈。
/// Advanced beauty effects, such as eye brightening, teeth whitening, and dark-circle reduction.
  UyaliBeautyFeatureBeauty = 2,
/// 人脸美型。
/// Face reshaping.
  UyaliBeautyFeatureReshape = 3,
/// 美体塑形。
/// Body reshaping.
  UyaliBeautyFeatureBody = 4,
/// 美妆效果。
/// Makeup effects.
  UyaliBeautyFeatureMakeup = 5,
/// 人脸关键点输出。
/// Face landmark output.
  UyaliBeautyFeatureFaceLandmarks = 6,
/// 人体姿态输出。
/// Body pose output.
  UyaliBeautyFeatureBodyPose = 7,
/// 调试信息输出。
/// Debug output.
  UyaliBeautyFeatureDebugOutputs = 8,
/// 自定义美妆素材。
/// Custom makeup assets.
  UyaliBeautyFeatureCustomMakeupAssets = 9,
};

@class NSDate;
/// License 激活或加载结果。
/// Result returned after activating or loading a license.
SWIFT_CLASS("_TtC14UyaliBeautySDK24UyaliBeautyLicenseResult")
@interface UyaliBeautyLicenseResult : NSObject
/// License 状态。
/// License status.
@property (nonatomic, readonly) enum UyaliBeautyLicenseStatus status;
/// 可展示或记录的状态说明。
/// Human-readable status message for display or logging.
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
/// License ID；未授权免费模式下为空。
/// License ID; nil in no-license free mode.
@property (nonatomic, readonly, copy) NSString * _Nullable licenseId;
/// 套餐 ID；未授权免费模式下为空。
/// Plan ID; nil in no-license free mode.
@property (nonatomic, readonly, copy) NSString * _Nullable planId;
/// License 过期时间；未授权免费模式下为空。
/// License expiration date; nil in no-license free mode.
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresAt;
/// 创建 License 结果。
/// Creates a license result.
- (nonnull instancetype)initWithStatus:(enum UyaliBeautyLicenseStatus)status message:(NSString * _Nonnull)message licenseId:(NSString * _Nullable)licenseId planId:(NSString * _Nullable)planId expiresAt:(NSDate * _Nullable)expiresAt OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// License 校验状态。
/// License validation status.
typedef SWIFT_ENUM_NAMED(NSInteger, UyaliBeautyLicenseStatus, "UyaliBeautyLicenseStatus", open) {
/// 未加载商业授权，默认免费模式已启用。
/// No commercial license is loaded; the default free mode is active.
  UyaliBeautyLicenseStatusFree = 0,
/// 商业 License 有效。
/// The commercial license is valid.
  UyaliBeautyLicenseStatusValid = 1,
/// License 格式无效或无法解析。
/// The license format is invalid or cannot be parsed.
  UyaliBeautyLicenseStatusInvalidFormat = 2,
/// License 签名校验失败。
/// The license signature verification failed.
  UyaliBeautyLicenseStatusInvalidSignature = 3,
/// License 使用了当前 SDK 不支持的签名算法。
/// The license uses a signature algorithm unsupported by this SDK.
  UyaliBeautyLicenseStatusUnsupportedAlgorithm = 4,
/// License 使用了当前 SDK 不信任的公钥 ID。
/// The license uses a public key ID that is not trusted by this SDK.
  UyaliBeautyLicenseStatusUnsupportedKey = 5,
/// License 不支持当前平台。
/// The license does not support the current platform.
  UyaliBeautyLicenseStatusPlatformUnsupported = 6,
/// License 与当前 App 标识不匹配。
/// The license does not match the current app identity.
  UyaliBeautyLicenseStatusAppMismatch = 7,
/// License 已过期。
/// The license has expired.
  UyaliBeautyLicenseStatusExpired = 8,
/// License 尚未到生效时间。
/// The license is not valid yet.
  UyaliBeautyLicenseStatusNotYetValid = 9,
/// 检测到本地时间回拨。
/// Local clock rollback was detected.
  UyaliBeautyLicenseStatusTimeRollback = 10,
/// License 不支持当前 SDK 版本。
/// The license does not support the current SDK version.
  UyaliBeautyLicenseStatusSdkVersionUnsupported = 11,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
